/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_blogss_core_jni_HelloJni */

#ifndef _Included_cn_blogss_core_jni_HelloJni
#define _Included_cn_blogss_core_jni_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_blogss_core_jni_HelloJni
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_blogss_core_jni_HelloJni_get
  (JNIEnv *, jobject);

/*
 * Class:     cn_blogss_core_jni_HelloJni
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_blogss_core_jni_HelloJni_set
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
