/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
/* Header for class cn_blogss_core_jni_HelloWorld */

#ifndef _Included_cn_blogss_core_jni_HelloWorld
#define _Included_cn_blogss_core_jni_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_blogss_core_jni_HelloWorld
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_blogss_core_jni_HelloWorld_print(JNIEnv *, jobject){
    printf("Hello World!\n");
    return ;
};

#ifdef __cplusplus
}
#endif
#endif
